#!/bin/bash
script_link="$( readlink "$BASH_SOURCE" )" || script_link="$BASH_SOURCE"
apparent_sdk_dir="${script_link%/*}"
if [ "$apparent_sdk_dir" == "$script_link" ]; then
  apparent_sdk_dir=.
fi
sdk_dir="$( command cd -P "$apparent_sdk_dir" > /dev/null && pwd -P )"

OPENCV_AI_CODE_ROOT="$( command cd -P "$sdk_dir/.." > /dev/null && pwd -P)"

# Update the digest to match the image you which to use.
if [ -z "$OPENCVAI_DEV_ENV_TAG" ]
then
    DIGEST=@sha256:d4d0aea0351c4080eecc94b302c8d1f84b3ce4c6e68e113a54ba615dab463e5d
else
    DIGEST=$OPENCVAI_DEV_ENV_TAG
fi

OPENCVAI_IMAGE=opencvai/dev_env14.04$DIGEST

# these forward the host's DISPLAY to the container.
FORWARD_DISPLAY_FLAGS=$(echo \
    --env="DISPLAY" \
    --volume="/etc/group:/etc/group:ro" \
    --volume="/etc/passwd:/etc/passwd:ro" \
    --volume="/etc/shadow:/etc/shadow:ro" \
    --volume="/etc/sudoers.d:/etc/sudoers.d:ro" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw"
)

# Add /opt/opencv_ai/bin to the path.
PATH_FLAGS=$(echo \
    --env="PATH=/opt/opencv_ai/bin:/usr/lib/llvm-3.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
)

docker run -it --rm \
        $PATH_FLAGS \
        $FORWARD_DISPLAY_FLAGS \
	-u=$(id -u ${USER}):$(id -g ${USER}) \
	-v $OPENCV_AI_CODE_ROOT:$OPENCV_AI_CODE_ROOT \
	-w=$(pwd) \
        $OPENCVAI_IMAGE \
	$@
